### ISSUE TITLE
Weird behaviour using useState

### ISSUE THREAD

**Issue by pablotz** [WrathChaos/react-native-single-select#14] opened 2021-11-13 03:57 UTC
I'm trying to set a state with the useState prop inside the function **"onSelect"**, but the selected object doesn't show in the component.

I fix it using initialValue

![Screenshot 2021-11-12 215737](https://user-images.githubusercontent.com/29645521/141604823-2bbb45d3-abee-409b-a90f-1221cc3609aa.png)

**Comment by kuraydev** [comment] 2021-11-13 09:57
Hello @pablotz 
I will take a look at this bug. Thank you so much :) 
Actually, it should handle itself. If you can, please share the reproducible example.

**Comment by pablotz** [comment] 2021-11-13 16:59
Thanks for your quickly reply. 
Sure, I make a small repository to make a fork of it, if you want to check it I reply the bug in there. 

if I'm wrong with something don't hesitate to let me know. 
[https://github.com/pablotz/selectBehaviour](url)

**Comment by mariomurrent-softwaresolutions** [comment] 2022-07-18 05:11
> Thanks for your quickly reply. Sure, I make a small repository to make a fork of it, if you want to check it I reply the bug in there.
> 
> if I'm wrong with something don't hesitate to let me know. [https://github.com/pablotz/selectBehaviour](url)

If you fork it, can you also open a PR, so that the bug fix can be merged in this repo?

If not already done :)

**Comment by mariomurrent-softwaresolutions** [comment] 2022-08-02 08:19
> I'm trying to set a state with the useState prop inside the function **"onSelect"**, but the selected object doesn't show in the component.
> 
> I fix it using initialValue
> 
> ![Screenshot 2021-11-12 215737](https://user-images.githubusercontent.com/29645521/141604823-2bbb45d3-abee-409b-a90f-1221cc3609aa.png)

But I actually think this is the correct behaviour and not a bug?

**Closed as completed** 2023-07-10 20:03 UTC
